USE symptom
;

SET FOREIGN_KEY_CHECKS=0;



DROP TABLE IF EXISTS CHECKIN CASCADE
;
DROP TABLE IF EXISTS CHECKIN_MEDICATION CASCADE
;
DROP TABLE IF EXISTS DOCTOR CASCADE
;
DROP TABLE IF EXISTS PATIENT CASCADE
;
DROP TABLE IF EXISTS PATIENT_MEDICATION CASCADE
;

CREATE TABLE CHECKIN
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CHECKIN_DATE DATETIME(0) NOT NULL,
	SEND BOOL NOT NULL DEFAULT 0,
	HOWBAD VARCHAR(50) NOT NULL,
	PAINSTOP VARCHAR(50) NOT NULL,
	TAKEMEDICATION BOOL NOT NULL,
	ALERTDOCTOR BOOL DEFAULT 0,
	PHOTO_PATH VARCHAR(500),
	ID_PATIENT BIGINT NOT NULL,
	PRIMARY KEY (ID),
	KEY (ID_PATIENT)

) 
;


CREATE TABLE CHECKIN_MEDICATION
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TAKEIT BOOL NOT NULL,
	TAKEIT_DATE TEXT,
	TAKEIT_TIME TEXT,
	ID_CHECKIN BIGINT NOT NULL,
	ID_PATIENTMEDICATION BIGINT NOT NULL,
	PRIMARY KEY (ID),
	KEY (ID_PATIENTMEDICATION),
	KEY (ID_CHECKIN)

) 
;


CREATE TABLE DOCTOR
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)

) 
;


CREATE TABLE PATIENT
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL,
	BIRTHDATE DATE,
	ID_DOCTOR BIGINT NOT NULL,
	PRIMARY KEY (ID),
	KEY (ID_DOCTOR)

) 
;


CREATE TABLE PATIENT_MEDICATION
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME TEXT NOT NULL,
	SEND BOOL NOT NULL DEFAULT 0,
	ACTIVE BOOL NOT NULL DEFAULT 1,
	ID_PATIENT BIGINT NOT NULL,
	PRIMARY KEY (ID),
	KEY (ID_PATIENT)

) 
;



SET FOREIGN_KEY_CHECKS=1;


ALTER TABLE CHECKIN ADD CONSTRAINT FK_CHECKIN_PATIENT 
	FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT (ID)
;

ALTER TABLE CHECKIN_MEDICATION ADD CONSTRAINT FK_CHECKIN_MEDICATION_MEDICATION 
	FOREIGN KEY (ID_PATIENTMEDICATION) REFERENCES PATIENT_MEDICATION (ID)
;

ALTER TABLE CHECKIN_MEDICATION ADD CONSTRAINT FK_CHECKIN_MEDICATION_CHECKIN 
	FOREIGN KEY (ID_CHECKIN) REFERENCES CHECKIN (ID)
;

ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_DOCTOR 
	FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR (ID)
;

ALTER TABLE PATIENT_MEDICATION ADD CONSTRAINT FK_PATIENT_MEDICATION_PATIENT 
	FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT (ID)
;
